from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

server = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Crystal', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal'}), 'ref_prefix':'Y', 'fplist':[''], 'footprint':'Crystal:Crystal_0603_1608Metric', 'keywords':'quartz ceramic resonator oscillator', 'description':'Two pin crystal', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'STM32C031C4Tx', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'STM32C031C4Tx'}), 'ref_prefix':'U', 'fplist':['Package_QFP:LQFP-48_7x7mm_P0.5mm', 'Package_QFP:LQFP-48_7x7mm_P0.5mm'], 'footprint':'Package_QFP:LQFP-48_7x7mm_P0.5mm', 'keywords':'Arm Cortex-M0+ STM32C0 STM32C0x1', 'description':'STMicroelectronics Arm Cortex-M0+ MCU, 16KB flash, 12KB RAM, 48 MHz, 2.0-3.6V, 45 GPIO, LQFP48', 'datasheet':'https://www.st.com/resource/en/datasheet/stm32c031c4.pdf', 'pins':[
            Pin(num='1',name='PC13',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='PF2',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='PA0',func=pin_types.BIDIR,unit=1),
            Pin(num='12',name='PA1',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='PA2',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='PA3',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='PA4',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='PA5',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='PA6',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='PA7',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='PB0',func=pin_types.BIDIR,unit=1),
            Pin(num='2',name='PC14',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='PB1',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='PB2',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='PB10',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='PB11',func=pin_types.BIDIR,unit=1),
            Pin(num='24',name='PB12',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='PB13',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='PB14',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='PB15',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='PA8',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='PA9/NC',func=pin_types.BIDIR,unit=1),
            Pin(num='3',name='PC15',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='PC6',func=pin_types.BIDIR,unit=1),
            Pin(num='31',name='PC7',func=pin_types.BIDIR,unit=1),
            Pin(num='32',name='PA10/NC',func=pin_types.BIDIR,unit=1),
            Pin(num='33',name='PA11/PA9',func=pin_types.BIDIR,unit=1),
            Pin(num='34',name='PA12/PA10',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='PA13',func=pin_types.BIDIR,unit=1),
            Pin(num='36',name='PA14',func=pin_types.BIDIR,unit=1),
            Pin(num='37',name='PA15',func=pin_types.BIDIR,unit=1),
            Pin(num='38',name='PD0',func=pin_types.BIDIR,unit=1),
            Pin(num='39',name='PD1',func=pin_types.BIDIR,unit=1),
            Pin(num='4',name='PF3',func=pin_types.BIDIR,unit=1),
            Pin(num='40',name='PD2',func=pin_types.BIDIR,unit=1),
            Pin(num='41',name='PD3',func=pin_types.BIDIR,unit=1),
            Pin(num='42',name='PB3',func=pin_types.BIDIR,unit=1),
            Pin(num='43',name='PB4',func=pin_types.BIDIR,unit=1),
            Pin(num='44',name='PB5',func=pin_types.BIDIR,unit=1),
            Pin(num='45',name='PB6',func=pin_types.BIDIR,unit=1),
            Pin(num='46',name='PB7',func=pin_types.BIDIR,unit=1),
            Pin(num='47',name='PB8',func=pin_types.BIDIR,unit=1),
            Pin(num='48',name='PB9',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='VREF+',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='7',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='8',name='PF0',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='PF1',func=pin_types.BIDIR,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'4001', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'4001'}), 'ref_prefix':'U', 'fplist':[''], 'footprint':'', 'keywords':'CMOS Nor2', 'description':'Quad Nor 2 inputs', 'datasheet':'http://www.intersil.com/content/dam/Intersil/documents/cd40/cd4000bms-01bms-02bms-25bms.pdf', 'pins':[
            Pin(num='1',name='~',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='~',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='~',func=pin_types.OUTPUT,unit=1),
            Pin(num='4',name='~',func=pin_types.OUTPUT,unit=2),
            Pin(num='5',name='~',func=pin_types.INPUT,unit=2),
            Pin(num='6',name='~',func=pin_types.INPUT,unit=2),
            Pin(num='10',name='~',func=pin_types.OUTPUT,unit=3),
            Pin(num='8',name='~',func=pin_types.INPUT,unit=3),
            Pin(num='9',name='~',func=pin_types.INPUT,unit=3),
            Pin(num='11',name='~',func=pin_types.OUTPUT,unit=4),
            Pin(num='12',name='~',func=pin_types.INPUT,unit=4),
            Pin(num='13',name='~',func=pin_types.INPUT,unit=4),
            Pin(num='14',name='VDD',func=pin_types.PWRIN,unit=5),
            Pin(num='7',name='VSS',func=pin_types.PWRIN,unit=5)], 'unit_defs':[{'label': 'uA', 'num': 1, 'pin_nums': ['1', '2', '3']},{'label': 'uB', 'num': 2, 'pin_nums': ['5', '4', '6']},{'label': 'uC', 'num': 3, 'pin_nums': ['8', '9', '10']},{'label': 'uD', 'num': 4, 'pin_nums': ['11', '12', '13']},{'label': 'uE', 'num': 5, 'pin_nums': ['14', '7']}] })])