from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

test_client = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)] }),
        Part(**{ 'name':'Crystal', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal'}), 'ref_prefix':'Y', 'fplist':[''], 'footprint':'Crystal:Crystal_0603_1608Metric', 'keywords':'quartz ceramic resonator oscillator', 'description':'Two pin crystal', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)] }),
        Part(**{ 'name':'ATSAME70J21A-AN', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ATSAME70J21A-AN'}), 'ref_prefix':'U', 'fplist':['Package_QFP:LQFP-64_10x10mm_P0.5mm'], 'footprint':'Package_QFP:LQFP-64_10x10mm_P0.5mm', 'keywords':'32-bit ARM Cortex-M7 MCU Microcontroller', 'description':'SAM E70 Microchip SMART ARM Cortex-M7-based MCU, 2048K Flash, 384K SRAM, LQFP64', 'datasheet':'http://ww1.microchip.com/downloads/en/DeviceDoc/SAM-E70-S70-V70-V71-Family-Data-Sheet-DS60001527D.pdf', 'pins':[
            Pin(num='64',name='VDDPLLUSB',func=pin_types.PWRIN,unit=1),
            Pin(num='40',name='PA3',func=pin_types.BIDIR,unit=1),
            Pin(num='34',name='PA4',func=pin_types.BIDIR,unit=1),
            Pin(num='32',name='PA5',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='PA7',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='PA8',func=pin_types.BIDIR,unit=1),
            Pin(num='33',name='PA9',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='PA10',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='PA11',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='PA12',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='PA13',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='PA14',func=pin_types.BIDIR,unit=1),
            Pin(num='12',name='PA21',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='PA22',func=pin_types.BIDIR,unit=1),
            Pin(num='23',name='PA24',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='PA27',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='PB0',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='PB1',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='PB2',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='PB3',func=pin_types.BIDIR,unit=1),
            Pin(num='46',name='PB4',func=pin_types.BIDIR,unit=1),
            Pin(num='47',name='PB5',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='PB6',func=pin_types.BIDIR,unit=1),
            Pin(num='39',name='PB7',func=pin_types.BIDIR,unit=1),
            Pin(num='62',name='PB8',func=pin_types.BIDIR,unit=1),
            Pin(num='63',name='PB9',func=pin_types.BIDIR,unit=1),
            Pin(num='38',name='PB12',func=pin_types.BIDIR,unit=1),
            Pin(num='60',name='DP',func=pin_types.BIDIR,unit=1),
            Pin(num='59',name='DM',func=pin_types.BIDIR,unit=1),
            Pin(num='37',name='TST',func=pin_types.INPUT,unit=1),
            Pin(num='36',name='NRST',func=pin_types.BIDIR,unit=1),
            Pin(num='45',name='JTAGSEL',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='VREFP',func=pin_types.INPUT,unit=1),
            Pin(num='10',name='VDDIO',func=pin_types.PWRIN,unit=1),
            Pin(num='42',name='VDDIO',func=pin_types.PASSIVE,unit=1),
            Pin(num='58',name='VDDIO',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='VDDCORE',func=pin_types.PWRIN,unit=1),
            Pin(num='24',name='VDDCORE',func=pin_types.PASSIVE,unit=1),
            Pin(num='61',name='VDDCORE',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='31',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='VDDOUT',func=pin_types.PWROUT,unit=1),
            Pin(num='4',name='VDDIN',func=pin_types.PWRIN,unit=1),
            Pin(num='52',name='VDDPLL',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='PD0',func=pin_types.BIDIR,unit=1),
            Pin(num='57',name='PD1',func=pin_types.BIDIR,unit=1),
            Pin(num='56',name='PD2',func=pin_types.BIDIR,unit=1),
            Pin(num='55',name='PD3',func=pin_types.BIDIR,unit=1),
            Pin(num='54',name='PD4',func=pin_types.BIDIR,unit=1),
            Pin(num='53',name='PD5',func=pin_types.BIDIR,unit=1),
            Pin(num='51',name='PD6',func=pin_types.BIDIR,unit=1),
            Pin(num='50',name='PD7',func=pin_types.BIDIR,unit=1),
            Pin(num='49',name='PD8',func=pin_types.BIDIR,unit=1),
            Pin(num='48',name='PD9',func=pin_types.BIDIR,unit=1),
            Pin(num='44',name='PD10',func=pin_types.BIDIR,unit=1),
            Pin(num='43',name='PD11',func=pin_types.BIDIR,unit=1),
            Pin(num='41',name='PD12',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='PD21',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='PD22',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='PD24',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='PD25',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='PD26',func=pin_types.BIDIR,unit=1),
            Pin(num='2',name='PD31',func=pin_types.BIDIR,unit=1)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)] }),
        Part(**{ 'name':'XTR111AxDGQ', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'XTR111AxDGQ'}), 'ref_prefix':'U', 'fplist':['Package_SO:MSOP-10-1EP_3x3mm_P0.5mm_EP2.2x3.1mm_Mask1.83x1.89mm_ThermalVias'], 'footprint':'Package_SO:MSOP-10-1EP_3x3mm_P0.5mm_EP2.2x3.1mm_Mask1.83x1.89mm_ThermalVias', 'keywords':'0-20mA 4-20mA Current Loop Transmitter Voltage To Current', 'description':'0-20mA/4-20mA Current Loop Transmitter, Precision Voltage-To-Current, MSOP-10', 'datasheet':'https://www.ti.com/lit/ds/symlink/xtr111.pdf', 'pins':[
            Pin(num='5',name='REGF',func=pin_types.OUTPUT,unit=1),
            Pin(num='4',name='REGS',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='VIN',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='SET',func=pin_types.PASSIVE,unit=1),
            Pin(num='1',name='VSP',func=pin_types.PWRIN,unit=1),
            Pin(num='10',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='11',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='OD',func=pin_types.INPUT,unit=1),
            Pin(num='8',name='~{EF}',func=pin_types.OPENCOLL,unit=1),
            Pin(num='2',name='IS',func=pin_types.OUTPUT,unit=1),
            Pin(num='3',name='VG',func=pin_types.OUTPUT,unit=1)] }),
        Part(**{ 'name':'AP33771', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP33771'}), 'ref_prefix':'U', 'fplist':['Package_DFN_QFN:QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm'], 'footprint':'Package_DFN_QFN:QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm', 'keywords':'USB Type C PD Sink', 'description':'USB Type-C PD Sink Controller, QFN-24', 'datasheet':'https://www.diodes.com/assets/Datasheets/AP33771.pdf', 'pins':[
            Pin(num='1',name='ISENP',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='CC1',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='CC2',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='VSEL0',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='VSEL1',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='VSEL2',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='PSEL',func=pin_types.BIDIR,unit=1),
            Pin(num='2',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='18',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='21',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='10',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='19',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='24',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='25',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='23',name='PWR_EN',func=pin_types.PWRIN,unit=1),
            Pin(num='22',name='VBUS',func=pin_types.PWRIN,unit=1),
            Pin(num='12',name='V3VD',func=pin_types.PWROUT,unit=1),
            Pin(num='20',name='V5V',func=pin_types.PWROUT,unit=1),
            Pin(num='14',name='VFB',func=pin_types.INPUT,unit=1),
            Pin(num='15',name='IFB',func=pin_types.INPUT,unit=1),
            Pin(num='8',name='GPIO1',func=pin_types.BIDIR,unit=1),
            Pin(num='6',name='GPIO4',func=pin_types.BIDIR,unit=1)] })])